import React from "react";

export const SelectCity = ({handleCity}) => {
    const cities = [
        "New York",
        "Los Angeles",
        "Chicago",
        "Houston",
        "Phoenix",
        "Philadelphia",
        "San Antonio",
        "San Diego",
        "Dallas",
        "San Jose",
        "Austin",
        "Jacksonville",
        "Fort Worth",
        "Columbus",
        "Charlotte",
        "Indianapolis",
        "San Francisco",
        "Seattle",
        "Denver",
        "Washington",
        "Boston",
        "El Paso",
        "Nashville",
        "Detroit",
        "Oklahoma City",
        "Portland",
        "Las Vegas",
        "Memphis",
        "Louisville",
        "Baltimore",
        "Milwaukee",
        "Albuquerque",
        "Tucson",
        "Fresno",
        "Sacramento",
        "Mesa",
        "Kansas City",
        "Atlanta",
        "Long Beach",
        "Omaha",
        "Raleigh",
        "Colorado Springs",
        "Miami",
        "Virginia Beach",
        "Oakland",
        "Minneapolis",
        "Tulsa",
        "Arlington",
        "New Orleans",
        "Wichita",
        "Cleveland",
        "Tampa",
        "Bakersfield",
        "Aurora",
        "Anaheim",
        "Honolulu",
        "Santa Ana",
        "Corpus Christi",
        "Riverside",
        "Lexington",
        "St. Louis",
        "Stockton",
        "Pittsburgh",
        "Anchorage",
        "Cincinnati",
        "Henderson",
        "Greensboro",
        "Plano",
        "Newark",
        "Lincoln",
        "Orlando",
        "Irvine",
        "Toledo",
        "Jersey City",
        "Chula Vista",
        "Durham",
        "Fort Wayne",
        "St. Petersburg",
        "Laredo",
        "Buffalo",
        "Madison",
        "Lubbock",
        "Chandler",
        "Scottsdale",
        "Reno",
        "Glendale",
        "Gilbert",
        "Winston-Salem",
        "North Las Vegas",
        "Norfolk",
        "Chesapeake",
        "Garland",
        "Irving",
        "Hialeah",
        "Fremont",
        "Boise",
        "Richmond",
        "Baton Rouge",
        "Spokane",
        "Des Moines",
        "Tacoma",
        "San Bernardino",
        "Modesto",
        "Fontana",
        "Santa Clarita",
        "Birmingham",
        "Oxnard",
        "Fayetteville",
        "Moreno Valley",
        "Rochester",
        "Glendale",
        "Huntington Beach",
        "Salt Lake City",
        "Grand Rapids",
        "Amarillo",
        "Yonkers",
        "Aurora",
        "Montgomery",
        "Akron",
        "Little Rock",
        "Huntsville",
        "Augusta",
        "Port St. Lucie",
        "Grand Prairie",
        "Columbus",
        "Tallahassee",
        "Overland Park",
        "Tempe",
        "McKinney",
        "Mobile",
        "Cape Coral",
        "Shreveport",
        "Frisco",
        "Knoxville",
        "Worcester",
        "Brownsville",
        "Vancouver",
        "Fort Lauderdale",
        "Sioux Falls",
        "Ontario",
        "Chattanooga",
        "Providence",
        "Newport News",
        "Santa Rosa",
        "Oceanside",
        "Salem",
        "Elk Grove",
        "Garden Grove",
        "Pembroke Pines",
        "Peoria",
        "Eugene",
        "Corona",
        "Cary",
        "Springfield",
        "Fort Collins",
        "Jackson",
        "Alexandria",
        "Hayward",
        "Lancaster",
        "Lakewood",
        "Clarksville",
        "Palmdale",
        "Salinas",
        "Springfield",
        "Hollywood",
        "Pasadena",
        "Sunnyvale",
        "Macon",
        "Kansas City",
        "Pomona",
        "Escondido",
        "Killeen",
        "Naperville",
        "Joliet",
        "Bellevue",
        "Rockford",
        "Savannah",
        "Paterson",
        "Torrance",
        "Bridgeport",
        "McAllen",
        "Mesquite",
        "Syracuse",
        "Midland",
        "Pasadena",
        "Murfreesboro",
        "Miramar",
        "Dayton",
        "Fullerton",
        "Olathe",
        "Orange",
        "Thornton",
        "Roseville",
        "Denton",
        "Waco",
        "Surprise",
        "Carrollton",
        "West Valley City",
        "Charleston",
        "Warren",
        "Hampton",
        "Gainesville",
        "Visalia",
        "Coral Springs",
        "Columbia",
        "Cedar Rapids",
        "Sterling Heights",
        "New Haven",
        "Stamford",
        "Concord",
        "Kent",
        "Santa Clara",
        "Elizabeth",
        "Round Rock",
        "Thousand Oaks",
        "Lafayette",
        "Athens",
        "Topeka",
        "Simi Valley",
        "Fargo",
        "Norman",
        "Columbia",
        "Abilene",
        "Wilmington",
        "Hartford",
        "Victorville",
        "Pearland",
        "Vallejo",
        "Ann Arbor",
        "Berkeley",
        "Richardson",
        "Odessa",
        "Midland",
        "Cambridge",
        "Round Rock",
        "Waco",
        "Inglewood",
        "Boulder",
        "Westminster",
        "Waterbury",
        "West Jordan",
        "Lewisville",
        "Dearborn",
        "Broken Arrow",
        "College Station",
        "Pearland",
        "Santa Maria",
        "El Cajon",
        "San Mateo",
        "Lewisville",
        "Rialto",
        "Davenport",
        "Lakeland",
        "Clovis",
        "Edison",
        "Sandy Springs",
        "Woodbridge",
        "Renton",
        "Davie",
        "West Palm Beach",
        "Manchester",
        "Gresham",
        "Sparks",
        "Lynn",
        "Miami Gardens",
        "South Bend",
        "Vista",
        "Greeley",
        "Daly City",
        "Pompano Beach",
        "Norwalk",
        "Burbank",
        "San Buenaventura (Ventura)",
        "Fairfield",
        "High Point",
        "West Covina",
        "Richmond",
        "Billings",
        "Murrieta",
        "Waterloo",
        "Cambridge",
        "Palatine",
        "Antioch",
        "Centennial",
        "Richardson",
        "Temecula",
        "Denton",
        "Berkeley",
        "El Monte",
        "Norman",
        "Fargo",
        "Columbia",
        "Pueblo",
        "Lowell",
        "West Jordan",
        "Gresham",
        "San Marcos",
        "Frisco",
        "Daly City",
        "Citrus Heights",
        "Hawthorne",
        "Kalamazoo",
        "Freeport",
        "Carson City",
        "La Mesa",
        "Edinburg",
        "Pasco",
        "Vacaville",
        "Brockton",
        "Roanoke",
        "Hillsboro",
        "Wyoming",
        "Erie",
        "Tuscaloosa",
        "Spokane Valley",
        "Rock Hill",
        "Bethlehem",
        "Wilmington",
        "Racine",
        "Greenville",
        "Kalamazoo",
        "Bowie",
        "Burbank",
        "Midland",
        "Evanston",
        "Elgin",
        "Syracuse",
        "Lawton",
        "Enid",
        "New Britain",
        "Avondale",
        "Eau Claire",
        "South Bend",
        "Goodyear",
        "Plymouth",
        "Rapid City",
        "Bloomington",
        "Lake Forest",
        "Napa",
        "Largo",
        "Westland",
        "Lorain",
        "Portsmouth",
        "Folsom",
        "Santa Barbara",
        "Cedar Park",
        "Missoula",
        "Boynton Beach",
        "Lynchburg",
        "Rocklin",
        "Laguna Niguel",
        "Redding",
        "Medford",
        "Schaumburg",
        "Fort Myers",
        "Blaine",
        "St. Charles",
        "Trenton",
        "Sandy",
        "South Suffolk",
        "Lawrence",
        "Lauderhill",
        "Roanoke",
        "Rio Rancho",
        "Yuma",
        "Orem",
        "Longmont",
        "Nampa",
        "Suffolk",
        "Livonia",
        "Hesperia",
        "Albany",
        "Brooklyn Park",
        "Lynn",
        "Gastonia",
        "Chico",
        "Miami Beach",
        "Redwood City",
        "Hemet",
        "Walnut Creek",
        "Lakeville",
        "Mount Vernon",
        "Huntsville",
        "National City",
        "Bloomington",
        "Highland",
        "Bethesda",
        "Decatur",
        "Rowlett",
        "Cheektowaga",
        "West Allis",
        "Port Arthur",
        "Waukesha",
        "Elkhart",
        "Mount Pleasant",
        "Kenosha",
        "Saginaw",
        "Asheville",
        "Milpitas",
        "Deerfield Beach",
        "Waltham",
        "Arlington Heights",
        "Iowa City",
        "Bellflower",
        "Youngstown",
        "Largo",
        "St. Joseph",
        "La Habra",
        "Santa Fe",
        "Bellingham",
        "Tuscaloosa",
        "Syracuse",
        "Shelton",
        "Cheyenne",
        "Johns Creek",
        "North Richland Hills",
        "Edmond",
        "Haverhill",
        "Roswell",
        "Sammamish",
        "Bryan",
        "Albany",
        "Farmington Hills",
        "Palo Alto",
        "Waukesha",
        "Gulfport",
        "Broomfield",
        "Lenexa",
        "Pocatello",
        "Edmonds",
        "Greenville",
        "Scranton",
        "Gastonia",
        "Lynwood",
        "Skokie",
        "Fayetteville",
        "Buffalo Grove",
        "Rancho Cordova",
        "Bradenton",
        "Saint Cloud",
        "Palm Coast",
        "Pasco",
        "Elkhart",
        "San Marcos",
        "Lauderdale Lakes",
        "Fountainebleau",
        "Kennewick",
        "Frederick",
        "Oshkosh",
        "Petaluma",
        "Goose Creek",
        "Palo Alto",
        "North Little Rock",
        "Glenview",
        "Elyria",
        "Pacifica",
        "Great Falls",
        "St. Peters",
        "Cedar Hill",
        "Union City",
        "Hattiesburg",
        "Littleton",
        "Apex",
        "Texarkana",
        "Bonita Springs",
        "Keller",
        "Harrisonburg",
        "Portage",
        "Goldsboro",
        "Kokomo",
        "Bismarck",
        "Dearborn Heights",
        "Yorba Linda",
        "Redlands",
        "Lakeville",
        "Medford",
        "Petaluma",
        "Alameda",
        "Lauderhill",
        "Minnetonka",
        "Cypress",
        "Coachella",
        "Maple Grove",
        "Enid",
        "Brentwood",
        "Galveston",
        "Woodland",
        "Cranston",
        "Royal Oak",
        "Middletown",
        "Plainfield",
        "Tigard",
        "Novi",
        "Grand Island",
        "New Braunfels",
        "Moore",
        "Springdale",
        "Taunton",
        "Coppell",
        "Hendersonville",
        "Davis",
        "Rockwall",
        "Ceres",
        "Greenwood",
        "Beaumont",
        "Mishawaka",
        "Wilson",
        "Oro Valley",
        "Bowie",
        "Port Orange",
        "DeSoto",
        "Blue Springs",
        "Smyrna",
        "Springfield",
        "Rogers",
        "Eastvale",
        "Carol Stream",
        "Bryan",
        "Covina",
        "Pittsburg",
        "Palm Desert",
        "Normal",
        "Hoboken",
        "La Mesa",
        "La Mirada",
        "Lake Elsinore",
        "Columbia",
        "Pico Rivera",
        "Chapel Hill",
        "Kannapolis",
        "Sanford",
        "Brentwood",
        "Bozeman",
        "Hattiesburg",
        "Conroe",
        "Plainfield",
        "Lakewood",
        "Perris",
        "Bell Gardens",
        "Bountiful",
        "Brookfield",
        "Cleveland",
        "Kirkland",
        "Manhattan",
        "Calexico",
        "Noblesville",
        "Middletown",
        "Valdosta",
        "Beloit",
        "Palm Springs",
        "Wheaton",
        "Huber Heights",
        "Valley Stream",
        "Northglenn",
        "Paramount",
        "Elmhurst",
        "Porterville",
        "DeKalb",
        "Bowie",
        "Owensboro",
        "Pine Bluff",
        "Kokomo",
        "Roseville",
        "Lebanon",
        "Glendora",
        "Burlington",
        "Rowlett",
        "San Marcos",
        "Burlington",
        "Stanton",
        "Brunswick",
        "Lehi",
        "Monterey Park",
        "Clifton",
        "Puyallup",
        "Waltham",
        "Canton",
        "Placentia",
        "Madison",
        "Sarasota",
        "Homestead",
        "Concord",
        "Grand Forks",
        "Glen Burnie",
        "Lancaster",
        "North Miami",
        "Delray Beach",
        "Naperville",
        "Peoria",
        "Coeur d'Alene",
        "Bend",
        "Coral Gables",
        "Independence",
        "Wheaton",
        "Rapid City",
        "Rock Hill",
        "Westland",
        "Davis",
        "Sierra Vista",
        "Doral",
        "Canton",
        "Harrisonburg",
        "Grove City",
        "Maricopa",
        "Palm Bay",
        "Brookhaven",
        "Wausau",
        "Sherman",
        "Auburn",
        "Moline",
        "Rockwall",
        "Edina",
        "Seminole",
        "Bryan",
        "New Brunswick",
        "Bolingbrook",
        "Park Ridge",
        "Owensboro",
        "Elmhurst",
        "Royal Oak",
        "Eden Prairie",
        "Lake Havasu City",
        "Tuscaloosa",
        "Manhattan",
        "Grand Island",
        "Goodyear",
        "Buffalo Grove",
        "Apache Junction",
        "Norwich",
        "Kearny",
        "Barnstable",
        "Wauwatosa",
        "Rancho Santa Margarita",
        "Brookfield",
        "Oro Valley",
        "Edina",
        "Commerce City",
        "Cathedral City",
        "Leander",
        "Calexico",
        "Salem",
        "Hoboken",
        "Lawrence",
        "Rancho Palos Verdes",
        "San Bruno",
        "Pflugerville",
        "San Gabriel",
        "Pittsburg",
        "Harrisburg",
        "La Quinta",
        "Lancaster",
        "Novato",
        "Grand Forks",
        "Huntersville",
        "Yorba Linda",
        "Stonecrest",
        "Roy",
        "Rancho Santa Margarita",
        "Montclair",
        "Galveston",
        "Milford",
        "Mount Prospect",
        "Pocatello",
        "Woodland",
        "Alpharetta",
        "Tigard",
        "Hempstead",
        "Tustin",
        "Carpentersville",
        "Henderson",
        "Pasco",
        "Bowling Green",
        "Mentor",
        "Missoula",
        "Redmond",
        "Woodbury",
        "Bossier City",
        "Petaluma",
        "Covington",
        "North Port",
        "Portage",
        "West Sacramento",
        "Farmington",
        "Palm Desert",
        "Grove City",
        "Harrisburg",
        "Canton",
        "Bradenton",
        "Sanford",
        "Hollywood",
        "Delray Beach",
        "Bolingbrook",
        "La Mirada",
        "Norwich",
        "Fort Myers",
        "Highland",
        "Milpitas",
        "Fountain Valley",
        "Kenner",
        "Haverhill",
        "North Lauderdale",
        "Lakewood",
        "Pontiac",
        "Mount Prospect",
        "Beverly",
        "Lake Oswego",
        "Jupiter",
        "Newark",
        "San Rafael",
        "Noblesville",
        "Titusville",
        "Wausau",
        "La Puente",
        "Monrovia",
        "Portage",
        "Coconut Creek",
        "Dublin",
        "Bradenton",
        "Wilson",
        "Peabody",
        "Bountiful",
        "Beverly",
        "Ankeny",
        "Rohnert Park",
        "Sheboygan",
        "Keller",
        "Wilmington",
        "Bismarck",
        "Peachtree Corners",
        "Smyrna",
        "Coral Terrace",
        "Madera",
        "Orland Park",
        "North Bethesda",
        "Hamilton",
        "St. Cloud",
        "Palm Beach Gardens",
        "Duncanville",
        "Blacksburg",
        "Bonita Springs",
        "Atlantic City",
        "Palm Beach Gardens",
        "Upland",
        "Kearny",
        "Peabody",
        "Mansfield",
        "Nashua",
        "Covina",
        "Strongsville",
        "Waltham",
        "Elmhurst",
        "Aliso Viejo",
        "Oak Lawn",
        "Santa Cruz",
        "Ellicott City",
        "Woodbury",
        "Port Orange",
        "Fountain Valley",
        "Cuyahoga Falls",
        "Plainfield",
        "Broomfield",
        "Cheyenne",
        "East Orange",
        "Missouri City",
        "Elkhart",
        "Ocala",
        "La Crosse",
        "Cedar Hill",
        "Cedar Falls",
        "Valdosta",
        "Stanton",
        "Cerritos",
        "Owensboro",
        "Revere",
        "Weymouth",
        "Twin Falls",
        "Hutchinson",
        "North Miami Beach",
        "Fort Pierce",
        "Cleveland Heights",
        "Columbus",
        "DeSoto",
        "Hattiesburg",
        "Olympia",
        "New Bedford",
        "Arcadia",
        "Summerville",
        "Coon Rapids",
        "Lacey",
        "Rowland Heights",
        "La Mesa",
        "Bozeman",
        "Belleville",
        "Sherman",
        "Clifton",
        "Lehi",
        "Hickory",
        "Buena Park",
        "Lakeville",
        "Portage",
        "Bonita Springs",
        "Oak Park",
        "Southaven",
        "North Miami",
        "Danbury",
        "Norwich",
        "Jeffersonville",
        "Wausau",
        "Willowbrook",
        "Hackensack",
        "Chapel Hill",
        "Portage",
        "Norwalk",
        "Smyrna",
        "Florence",
        "Yorba Linda",
        "Oro Valley",
      ]
 
    
      return (    
        <select name="options" onChange={(event) => handleCity(event.target.value)}>
            {cities.map((city) => (
                <option key={city} value={city}>{city}</option>
            ))}
        </select>
    );
    
    
};
